@BadApi_HostAddress = http://localhost:5062
@username = alice
@password = alicepw

### Login
POST {{BadApi_HostAddress}}/account/login
Authorization: Basic {{username}} {{password}}

### Reset my password
POST {{BadApi_HostAddress}}/account/password
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

"newpassword"

### List users
GET {{BadApi_HostAddress}}/users



