@BadApi_HostAddress = http://localhost:5062

### Inspect user
GET {{BadApi_HostAddress}}/users/1
Authorization: Basic claire admin

### v1 : Very bad - it works, but...
POST {{BadApi_HostAddress}}/overposting/updatenamev1
Content-Type: application/json

{
    "Id": 1,
    "name": "All your bases are belong to us"
}

### v1 : Very bad - no validation of the name
POST {{BadApi_HostAddress}}/overposting/updatenamev1
Content-Type: application/json

{
  "Id": 1,
  "name": ""
}

### v1 : Very bad - make user admin
POST {{BadApi_HostAddress}}/overposting/updatenamev1
Content-Type: application/json

{
  "Id": 1,
  "name": "God mode!",
  "roles": ["developer","admin"]
}

### v1: Very bad - create new user
POST {{BadApi_HostAddress}}/overposting/updatenamev1
Content-Type: application/json

{
  "name": "New admin",
  "roles": ["admin"]
}

### v1: Very bad - update other user
POST {{BadApi_HostAddress}}/overposting/updatenamev1
Content-Type: application/json

{
  "Id": 2,
  "name": "Pwned"
}

### v2: Fixed
POST {{BadApi_HostAddress}}/overposting/updatenamev2
Content-Type: application/json

{
  "id": 1,
  "name": "Alicia"
}

### v2: Fixed - no empty name allowed
POST {{BadApi_HostAddress}}/overposting/updatenamev2
Content-Type: application/json

{
    "id": 1,
    "name": ""
}

### v2: Fixed - additional fields are ignored
POST {{BadApi_HostAddress}}/overposting/updatenamev2
Content-Type: application/json

{
  "id": 1,
  "name": "Alice Cooper",
  "roles": ["admin"]
}

### Fixed - only exisiting entity can be updated
POST {{BadApi_HostAddress}}/overposting/updatenamev2
Content-Type: application/json

{
    "Id": 0,
    "name": "New user"
}

### Fixed - targeted update
POST {{BadApi_HostAddress}}/overposting/updatenamev3
Content-Type: application/json

{
  "Id": 1,
  "name": "Alice"
}