@BadApi_HostAddress = http://localhost:5062

### List users
GET {{BadApi_HostAddress}}/users
Authorization: Basic claire admin

### Very bad 1 - it works, but...
POST {{BadApi_HostAddress}}/overposting/updatenamev1
Content-Type: application/json

{
    "Id": 1,
    "name": "All your base are belong to us"
}

### Very bad 1 - no validation of the name
POST {{BadApi_HostAddress}}/overposting/updatenamev1
Content-Type: application/json

{
  "Id": 1,
  "name": ""
}

### Very bad 1 - make user admin
POST {{BadApi_HostAddress}}/overposting/updatenamev1
Content-Type: application/json

{
  "Id": 1,
  "name": "All your base are belong to us",
  "roles": ["developer","admin"]
}

### Very bad 1 - create new user
POST {{BadApi_HostAddress}}/overposting/updatenamev1
Content-Type: application/json

{
  "name": "New admin",
  "roles": ["admin"]
}

### Fixed
POST {{BadApi_HostAddress}}/overposting/updatenamev2
Content-Type: application/json

{
  "Id": 1,
  "name": "Alicia"
}

### Fixed - no empty name allowed
POST {{BadApi_HostAddress}}/overposting/updatenamev2
Content-Type: application/json

{
    "Id": 1,
    "name": ""
}

### Fixed - additional fields are ignored
POST {{BadApi_HostAddress}}/overposting/updatenamev2
Content-Type: application/json

{
  "id": 1,
  "name": "Alice Cooper",
  "roles": ["admin"]
}

### Fixed - only exisiting entity can be updated
POST {{BadApi_HostAddress}}/overposting/updatenamev2
Content-Type: application/json

{
    "Id": 0,
    "name": "New user"
}