@BadApi_HostAddress = http://localhost:5062

### XXE : Bad

POST {{BadApi_HostAddress}}/xxe/bad
Content-Type: application/xml

<!DOCTYPE data [
        <!ENTITY file SYSTEM "file:///tmp/testxxe">
        ]>
<user>&file;</user>


### XXE : Proper deserialization
POST {{BadApi_HostAddress}}/xxe/good/
Content-Type: application/xml

<!DOCTYPE data [
        <!ENTITY file SYSTEM "file:///tmp/testxxe">
        ]>
<user>&file;</user>
